name: Deploy 

on:
  workflow_run:
    workflows: [Build and Push to Amazon ECS]
    types: [completed]
    branches: ["main"]

concurrency:
  group: terraform-dev
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1                  
  ECR_REPOSITORY: backend
  TF_WORKING_DIR: .
  API_DOMAIN_NAME: api.orema-devops.xyz

jobs:
  deploy-success:
    name: Deploy Backend to ASG success
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         role-to-assume: arn:aws:iam::556173312932:role/githubterraformrolec68d2e0fcf6ada69a6b12579b3
         aws-region:  us-east-1

    
      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Get image tag
        id: image
        run: |
          IMAGE_TAG="${{ github.event.workflow_run.head_sha }}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"
          echo "Deploying image:"
          echo "$IMAGE_TAG"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.7
      
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init --reconfigure


      - name: Select Terraform workspace
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform workspace select dev || terraform workspace new dev

      - name: Create Terraform variables
        run: |
          cat > terraform.tfvars <<EOF
          region                  = "us-east-1"
          enable_dns_hostnames    = true
          map_public_ip_on_launch = true
          availability_zone       = ["us-east-1a", "us-east-1b"]
          cidr_block              = "10.0.0.0/16"
          cidr_ipv4               = "0.0.0.0/0"
          device_name             = "/dev/xvda"
          image_id                = "ami-0b6d9d3d33ba97d99"
          private_dns_enabled     = true
          aws_account_id          = "556173312932"
          storage_type            = "gp2"
          engine_version          = "17"
          db_name                 = "mydatabase"
          domain_name             = "orema-devops.xyz"
          bucket_name             = "frontend-bucket-version-9250"
          api_domain_name         = "api.orema-devops.xyz"
          ecr_image_tag           = "${{ github.sha }}"
          EOF


      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -input=false -var="api_domain_name=$API_DOMAIN_NAME" -var="ecr_image_tag=$IMAGE_TAG" -out=tfplan

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -input=false -auto-approve tfplan 

      - name: Verify Application
        run: |
          echo "Waiting for app to become healthy"

          for i in {1..20}; do
            STATUS=$(curl --fail --silent https://api.orema-devops.xyz/health || true)

            echo "Response: $STATUS"

            if [ "$STATUS" = '{"status":"healthy"}' ]; then
              echo "Application is healthy!"
              exit 0
            fi

            echo "Application not ready. Attempt $i/20 failed..."
            sleep 15
          done

          echo "Application Health Verification Failed"
          exit 1